### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by krisu5** [vvye/smw-font#1]
As I commented on YouTube:

> I noticed that license info for the font is missing in the GitHub. Without it, technically you don't allow use of the font by anyone. I'm not sure though if you can license it as commercially usable, since it's edit of SMW's UI typeface. Safe bet is to license it as personal use only.

Possibly [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.en)? Downside with this license is the need of attribution, but it's best common one I could find right now.

**Comment by vvye** [comment]
Ah right, licenses.

I'm not big on legal stuff, not do I particularly care about attribution for this font, but what you said makes sense, so I went ahead and made it CC BY-NC. Hope that solves it (:
