### ISSUE TITLE
Extending language support (w/ Polish glyphs & in general)

### ISSUE THREAD

**Issue by jakubmanczak** [vvye/smw-font#2]
Hi there! Loved the video and really looking forward to using this font. As mentioned, it supports multiple languages, but unfortunately, it doesn't include Polish. I see that the font is open to personal edits as noted in the readme - but would you be open to contributions that extend the character support?

**Comment by vvye** [comment]
Sure, I don't see why not! I'm new to managing a repo, but I've just added contibuting info/instructions. Hope they make sense!

**Comment by vvye** [comment]
Going to go ahead and close this - if you run into any trouble contributing, feel free to open another issue and let me know (:
